name: Bingo
version: '${project.version}'
main: me.duoly.bingo.Main
api-version: 1.18
authors: [ Klaudiusz kor3nt Jędrzejczyk, Patryk F4s0la Grzesik, Patryk P3CZRI6 Jędrzejczyk ]

commands:
  generate:
