name: Bingo
version: 1.0.0
main: me.duoly.bingo.Main
authors: [ Klaudiusz kor3nt Jędrzejczyk, Patryk Misiris Grzesik, Patryk P3CZRI6 Jędrzejczyk ]
commands:
  druzyna:
    permission: bingo.teamAdmin
  party:
    permission: bingo.party
  admin:
    permission: admin.start
