name: Bingo
version: 1.2.1
main: me.duoly.bingo.Main
authors: [ Klaudiusz kor3nt Jędrzejczyk, Patryk Misiris Grzesik, Patryk P3CZRI6 Jędrzejczyk ]
api-version: 1.17
commands:
  zadania:
  rejoin:
  party:
  pomoc:
  add:
    permission: admin.game
  druzyna:
    permission: bingo.teamAdmin
  admin:
    permission: admin.start
  generate:
    permission: admin.generate
  world:
    permission: admin.generate
  check:
    permission: admin.generate
  accept:
    permission: admin.generate
  deny:
    permission: admin.generate
